src/lirc_pi/controller/urls.py
from django.conf.urls import url

from lirc_pi.controller import views

urlpatterns = [
    url(r'^$', views.TVRemoconView.as_view(), name='tv_remocon'),
]

src/lirc_pi/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',
        TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^controller/',
        include('lirc_pi.controller.urls', namespace='controller')),
]

src/lirc_pi/controller/models.py
from django.db import models

# Create your models here.

src/lirc_pi/controller/views.py
import subprocess

from django.conf import settings
from django.http import JsonResponse
from django.views.generic import TemplateView


class RemoconViewBase(TemplateView):
    btn_prefix = ''
    remocon_name = ''

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not settings.DEBUG and \
           self.get_remocon_name() not in self.get_remocon_info():
            raise ValueError

    def get_remocon_name(self):
        return self.remocon_name

    def issue_command(self, *args):
        return subprocess.run(
            ['irsend', *args],
            stdout=subprocess.PIPE
        )

    def get_remocon_info(self, name='', btn=''):
        return self.issue_command(
            'LIST', name, btn
        ).stdout.decode().rstrip().split('\n')

    def get_button_name(self):
        return list(map(
            lambda x: x.split()[1],
            self.get_remocon_info(self.get_remocon_name())
        ))

    def send_once(self, btn, count=1):
        return self.issue_command(
            '--count=%d' % count,
            'SEND_ONCE',
            self.get_remocon_name(),
            btn,
        )

    def post(self, request, *args, **kwargs):
        btn = request.POST.get('name', '')

        if hasattr(self, self.btn_prefix + btn):
            getattr(self, self.btn_prefix + btn)(btn)
        elif btn in self.get_button_name():
            self.send_once(btn)
        return JsonResponse({})


class TVRemoconView(RemoconViewBase):
    remocon_name = 'tv'
    template_name = 'controller/remocon.html'

    def on(self, btn):
        """
        when AQUOS is off for a while,
        power signal should be sent more than 1 time.
        """
        self.send_once('power', count=3)

    def off(self, btn):
        self.send_once('power')

src/lirc_pi/controller/templates/controller/remocon.html
{% extends "base.html" %}

{% load static %}

{% block head %}
<script type="text/javascript" src="{% static 'js/btn-ajax.js' %}"></script>
{% endblock %}

{% block stylesheet %}
<style type="text/css">
.btn-ajax {
  margin: 1px 0px;
  width: 30px;
  height: 30px;
  text-align: center;
  padding: 6px 0;
  font-size: 12px;
  line-height: 1.428571429;
  border-radius: 30px;
}
</style>
{% endblock %}

{% block script %}
<script type="text/javascript">
  $(function(){
    $(document).keypress(function(e){
      var btn = '';

      // '1' ~ '9' keys
      if (e.which >= 49 && e.which <= 57) {
        btn = e.which - 48;  // 48 is '0' key
      }

      var which = {
        48: 10,  // '0' key
        45: 11,  // '-' key
        94: 12,  // '^' key
      };

      if (e.which in which) {
        btn = which[e.which]
      }

      if (btn) {
        $('[name=' + btn + 'ch]').trigger('click');
        return;
      }

      var keyCode = {
        13: 'enter',
        37: 'left',
        38: 'up',
        39: 'right',
        40: 'down',
      };

      if (e.keyCode in keyCode) {
        btn = keyCode[e.keyCode]
      }

      if (btn) {
        e.preventDefault();
        $('[name=' + btn + ']').trigger('click');
        return;
      }
    });
  });
</script>
{% endblock %}


{% block content %}

<div class="row">
  <div class="offset-lg-3 col-lg-6 offset-md-2 col-md-8 offset-sm-1 col-sm-10 col-12">
    <br>
    <form method="post" action="{% url 'controller:tv_remocon' %}">
      <div class="container">
	{% csrf_token %}
	<div class="row">
	  <div class="col-4">
	    <div class="row">
	      <input class="btn btn-danger btn-ajax col-6" type="submit" name="on" value="ON" style="height: 60px;">
	      <input class="btn btn-secondary btn-ajax col-6" type="submit" name="off" value="OFF" style="height: 60px;">
	    </div>
	  </div>
	  <div class="col-8">
	    <div class="row">
	      <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="regular_program" value="常連番組">
	      <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="display_info" value="画面表示">
	      <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="internet" value="インターネット">
	      <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="subtitiles" value="字幕">
	      <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="catv" value="3桁入力">
	      <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="vod" value="VOD操作">
	    </div>
	  </div>
	</div>
	<br>

	<div class="row">
	  <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="1ch" value="1">
	  <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="2ch" value="2">
	  <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="3ch" value="3">
	  <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="4ch" value="4">
	  <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="5ch" value="5">
	  <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="6ch" value="6">
	  <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="7ch" value="7">
	  <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="8ch" value="8">
	  <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="9ch" value="9">
	  <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="10ch" value="10">
	  <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="11ch" value="11">
	  <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="12ch" value="12">
	</div>
	<br>

	<div class="row">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="isdbt_d" value="地上D">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="bs" value="BS">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="cs" value="CS">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="isdbt_a" value="地上A">
	</div>
	<br>

	<div class="row">
	  <div class="col-3"></div>
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="volume_up" value="+">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="channel_next" value="+">
	  <div class="col-3"></div>
	</div>
	<div class="row">
	  <div class="col-1"></div>
	  <input class="btn btn-sm btn-secondary btn-ajax col-2" type="submit" name="mute" value="消音">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3 disabled" type="button" name="" value="音量">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3 disabled" type="button" name="" value="選局">
	  <input class="btn btn-sm btn-secondary btn-ajax col-2" type="submit" name="switch_input" value="入力切換">
	  <div class="col-1"></div>
	</div>
	<div class="row">
	  <div class="col-3"></div>
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="volume_down" value="-">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="channel_prev" value="-">
	  <div class="col-3"></div>
	</div>
	<br>

	<div class="row">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="d_button" value="d データ連動">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="av_position" value="AVポジション">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="off_timer" value="オフタイマー">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="familink" value="ファミリンク">
	</div>
	<br>

	<div class="row">
	  <input class="btn btn-secondary btn-ajax col-6" type="submit" name="listings" value="番組表">
	  <input class="btn btn-secondary btn-ajax col-6" type="submit" name="home" value="ホーム">
	</div>
	<br>

	<div class="row">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="program_info" value="番組情報">
	  <div class="col-3"></div>
	  <div class="col-3"></div>
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="tool" value="ツール">
	</div>
	<div class="row">
	  <div class="col-4"></div>
	  <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="up" value="↑">
	  <div class="col-4"></div>
	</div>
	<div class="row">
	  <div class="col-1"></div>
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="left" value="←">
	  <div class="col-1"></div>
	  <input class="btn btn-sm btn-secondary btn-ajax col-2" type="submit" name="enter" value="決定">
	  <div class="col-1"></div>
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="right" value="→">
	  <div class="col-1"></div>
	</div>
	<div class="row">
	  <div class="col-4"></div>
	  <input class="btn btn-sm btn-secondary btn-ajax col-4" type="submit" name="down" value="↓">
	  <div class="col-4"></div>
	</div>
	<div class="row">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="end" value="終了">
	  <div class="col-3"></div>
	  <div class="col-3"></div>
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="back" value="戻る">
	</div>
	<br>

	<div class="row">
	  <input class="btn btn-sm btn-primary btn-ajax col-3" type="submit" name="blue" value="　">
	  <input class="btn btn-sm btn-danger btn-ajax col-3" type="submit" name="red" value="　">
	  <input class="btn btn-sm btn-success btn-ajax col-3" type="submit" name="green" value="　">
	  <input class="btn btn-sm btn-warning btn-ajax col-3" type="submit" name="yellow" value="　">
	</div>
	<br>

	<div class="row">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="save_mode" value="セーブモード">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="change_size" value="画面サイズ">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="switch_video" value="映像切換">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="switch_audio" value="音声切換">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="capture_screen" value="静止">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="portal" value="ポータル">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="half_screen" value="2画面">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="switch_control" value="操作切換">
	  <input class="btn btn-sm btn-danger btn-ajax col-3" type="submit" name="recorder_power" value="レコーダ電源">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="rewind" value="早戻し">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="play" value="再生">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="forward" value="早送り">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="function_menu" value="機能選択">
	  <input class="btn btn-sm btn-danger btn-ajax col-3" type="submit" name="start_recording" value="録画●">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="stop_recording" value="録画停止">
	  <input class="btn btn-sm btn-secondary btn-ajax col-3" type="submit" name="stop" value="停止■">
	</div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

src/lirc_pi/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
  <head>
    <meta charset="UTF-8">
    <title>リモコン</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="apple-touch-icon" href="{% static 'img/apple-touch-icon.png' %}" />
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block head %}{% endblock %}
    {% block stylesheet %}{% endblock %}
    {% block script %}{% endblock %}
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<a class="navbar-brand" href="{% url 'index' %}">Remocon</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
	  <span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarText">
	  <ul class="navbar-nav mr-auto">
	    <li class="nav-item active">
              <a class="nav-link" href="{% url 'controller:tv_remocon' %}">TV</a>
	    </li>
	    <li class="nav-item">
              <a class="nav-link" href="#">Light</a>
	    </li>
	  </ul>
	  <span class="navbar-text">
	    version 1.0
	  </span>
	</div>
      </nav>
    </header>
    <main>
      <div class="container">
	{% block content %}
	{% endblock %}
      </div>
    </main>
    <footer>
    </footer>
  </body>
</html>

src/lirc_pi/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
{% endblock %}

{% block content %}
<br>
<div class="">
  <div class="row">
    <div class="col">
      <center>
	<a href="{% url 'controller:tv_remocon' %}" style="color: #343a40;">
	  <i class="material-icons" style="font-size: 4rem;">tv</i>
	  <br>
	  AQUOS
	</a>
      </center>
    </div>
    <div class="col">
      <center>
	<a href="#!" style="color: gray;">
	  <i class="material-icons" style="font-size: 4rem;">wb_incandescent</i>
	  <br>
	  Light
	</a>
      </center>
    </div>
    <div class="col">
      <center>
	<a href="#!" style="color: gray;">
	  <i class="material-icons" style="font-size: 4rem;">toys</i>
	  <br>
	  AC
	</a>
      </center>
    </div>
    <div class="col">
      <center>
	<a href="#!" style="color: gray;">
	  <i class="material-icons" style="font-size: 4rem;">lock</i>
	  <br>
	  coming soon...
	</a>
      </center>
    </div>
  </div>
</div>
{% endblock %}